packages:
  - packages/*
  - apps/*
  - tools/*

allowBuilds:
  '@prisma/engines': true
  '@rocicorp/zero-sqlite3': true
  esbuild: true
  fsevents: true
  msgpackr-extract: true
  msw: true
  prisma: true
  protobufjs: true
  sharp: true

onlyBuiltDependencies:
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - fsevents
  - msgpackr-extract
  - msw
  - prisma
  - protobufjs
  - sharp
