packages:
  - packages/*
  - apps/*
  - tools/*

onlyBuiltDependencies:
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - fsevents
  - msgpackr-extract
  - msw
  - prisma
  - protobufjs
  - sharp
