version: "0.5"
is_strict: true

processes:
  #
  # Apps
  #

  www:
    command: "pnpm apps:www dev --port 4321"

  main:
    command: "pnpm apps:main dev"
    environment:
      - DB_URL=postgres://ktb:ktb@localhost:5432/ktb_development
      - GITHUB_OAUTH_REDIRECT_URI=https://ktb.localhost/auth/github/callback
      - MAIN_ORIGIN=https://ktb.localhost
      - PORT=5173
      - REDIS_URL=redis://localhost:6379
      - ZERO_CACHE_URL=https://zero.ktb.localhost
    depends_on:
      nginx:
        condition: process_started
      postgresql:
        condition: process_healthy
      valkey:
        condition: process_started

  zero-cache:
    command: "pnpm apps:main exec zero-cache-dev --query-forward-cookies --mutate-forward-cookies"
    environment:
      - ZERO_MUTATE_URL=http://localhost:5173/api/zero/mutate
      - ZERO_QUERY_URL=http://localhost:5173/api/zero/query
      - ZERO_UPSTREAM_DB=postgres://ktb:ktb@localhost:5432/ktb_development
    depends_on:
      postgresql:
        condition: process_healthy

  #
  # Tools
  #

  prisma-studio:
    command: "pnpm prisma studio --browser none"
    environment:
      - DB_URL=postgres://ktb:ktb@localhost:5432/ktb_development
    depends_on:
      nginx:
        condition: process_started
      postgresql:
        condition: process_healthy
