fullnameOverride: ktb

# This resource is global to the cluster and must be created ahead of time.
clusterIssuerName: ktb-letsencrypt-issuer

baseDomain: example.com

wwwBucketHostname: example.cdn.com

mainEnvVars:
  DB_SSL_NO_VERIFY: "true"
  DB_URL:
  GITHUB_OAUTH_CLIENT_ID:
  GITHUB_OAUTH_CLIENT_SECRET:
  GITHUB_OAUTH_REDIRECT_URI: https://ktb.example.com/auth/github/callback
  MAIN_ORIGIN: https://ktb.example.com
  REDIS_URL:
  SESSION_SECRET:
